---
authors:
  - Ansible Network Community (ansible-network)
license_file: LICENSE
name: junos
namespace: junipernetworks
readme: README.rst
repository: https://github.com/ansible-network/ansible_collections.junipernetworks.junos
